module.exports = {
  START_GAME: 'START_GAME',
  OPEN_CELL: 'OPEN_CELL',
  CLICK_MINE: 'CLICK_MINE',
  FLAG_CELL: 'FLAG_CELL',
  NORMALIZE_CELL: 'NORMALIZE_CELL',
  INCREASE_TIMER: 'INCREASE_TIMER'
};
